export const list = [
  'All',
  'Aberdeen & North Mgt',
  'Aberdeenshire North Relief',
  'Branch Management North Aberdeenshire & City',
  'Cornerstone SDS-Aberdeenshire',
  'Peterhead Connects',
  'Peterhead Harbour',
  '729 Club',
  'Aberdeen & Shire South Mgt',
  'Aberdeen City Relief',
  'Aberdeen Playscheme',
  'Aberdeen Sheltered Housing',
  'Aberdeen South CM2000',
  'Aberdeenshire South Relief',
  'Branch Management South Aberdeenshire & City',
  'Employment Service - Disco',
  'Employment Service North',
  'North Office',
  'Payroll Bureau',
  'Branch Management Ayrshire',
  'Butterfly Club',
  'Sanderson Avenue 9',
  'Shared Lives East Ayrshire',
  'Shared Lives Falkirk',
  'Shared Lives North Ayrshire',
  'Shared Lives South Ayrshire',
  'Branch Management Fife, Lothian & Borders',
  'Fife Office',
  'Fife Relief',
  'Forrest Walk Respite',
  'In Your Corner',
  'Lothian & Borders Mgt',
  'XxxShared Lives Edinburgh',
  'Branch Management Glasgow & East Dunbartonshire',
  'Broadleys Avenue 42',
  'East Dunbartonshire Relief',
  'Finding a Voice',
  'Glasgow & East Dun Mgt',
  'Glasgow City Relief',
  'Glasgow Community Justice',
  'Glasgow Peripatetic Team',
  'Mill St (IM-ILF)',
  'Partnership Project',
  'Shared Lives Glasgow',
  'Springfield Rd 69',
  'The Lens Sis-Bro',
  'Branch Management Moray',
  'Doocot View',
  'Moray Relief',
  'Moray Social Inclusion (Cornerstone SDS)',
  'Slioch',
  'Branch Management North Lanarkshire CS',
  'Cornerstone Connect',
  'NL CS Care Monitoring Services',
  'North Lanarkshire CS Relief',
  'Branch Management North Lanarkshire SL',
  'Coatbridge 2',
  'Cumbernauld 2',
  'North Lanarkshire SL Relief',
  'Xxx Shared Lives North Lanarkshire (Ayrshire)',
  'Branch Management Perth Dundee & Angus',
  'Dundee & Perth Mgt',
  'Dundee Connects',
  'Dundee Flexible Support',
  'Dundee Relief',
  'Dundee Transitions Service',
  'Perth Relief',
  'Branch Management WestDunbartonshire Argyll & Bute',
  'Can Care',
  'Carman Cafe',
  'Carman Centre',
  'Carman Connects',
  'Craigton Street',
  'Methlan Park - 6',
  'Waterfront',
  'West Dun - Day Opportunities',
  'West Dun - Homecare',
  'West Dun - Relief',
  'West Dun - Shortbreaks',
  'West Dunbarts Mgt',
  'XxxShared Lives West Dunbartonshire'
];
